# base image
FROM node:12.2.0-alpine

# set working directory
WORKDIR /usr/src/app/

ENV PATH /usr/src/app/node_modules/.bin:$PATH

# install and cache app dependencies
COPY package.json /usr/src/app/package.json
RUN yarn install

# start app
CMD ["yarn", "start"]