FROM node:12.2.0-alpine

# set working directory
WORKDIR /usr/src/app/

ENV PATH /usr/src/app/node_modules/.bin:$PATH

# install and cache app dependencies
COPY package.json /usr/src/app/package.json
RUN yarn install --silent
RUN yarn global add react-scripts@3.4.1 --silent

# start app
CMD ["yarn", "start"]

