version: "3"
services:
  server_prod:
    image: server:prod
    container_name: server_prod
    restart: always
    build: .
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=production
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo:latest
    ports:
      - "27017:27017"